---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schema:
    users:
      id:
        type: integer
        nullable: false
      email:
        type: string
        nullable: false
    sessions:
      email:
        type: string
        nullable: false
      access_token:
        type: string
        nullable: false
    errors:
      errors:
        type: string
paths:
  "/sessions/signin":
    post:
      summary: sign in API
      tags:
      - Session/signin
      parameters: []
      responses:
        '200':
          description: Created
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  nullable: false
                  default: test-user@example.com
                password:
                  type: string
                  nullable: false
                  default: '123456'
  "/users":
    post:
      summary: create user API
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: Created
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  nullable: false
                  default: user-test@example.com
                password:
                  type: string
                  nullable: false
                  default: '123456'
                password_confirmation:
                  type: string
                  nullable: false
                  default: '123456'
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: ''
